version: 2
updates:
  # Keep npm and yarn dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Update GitHub Actions versions if you add workflows in the future
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
