apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-blue
  labels:
    app: loanserve
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loanserve
      color: blue
  template:
    metadata:
      labels:
        app: loanserve
        color: blue
    spec:
      containers:
      - name: api
        image: loanserve/api:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEPLOY_COLOR
          value: "blue"
        envFrom:
        - secretRef:
            name: loanserve-secrets
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-blue
  labels:
    app: loanserve
    color: blue
spec:
  selector:
    app: loanserve
    color: blue
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP