apiVersion: v1
kind: ConfigMap
metadata: { name: loanserve-core-config }
data:
  NODE_ENV: "staging"
  SERVICE_NAME: "loanserve-core"
  HTTP_PORT: "8080"
  RABBIT_HEARTBEAT_SEC: "30"
  RABBIT_PREFETCH: "10"
  RABBIT_RECONNECT_MAX: "10"
  RABBIT_RECONNECT_BASE_MS: "5000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  OTEL_SAMPLING_RATIO: "1"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=loanserve-core,service.namespace=servicing,service.version=0.0.1"
  LOG_LEVEL: "info"
  LOG_PRETTY: "false"